name: Hello

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World - CI is working!"
      
    - name: Success
      run: echo "✅ CI Pipeline is working!"